version: 2.1

orbs:
  docker: circleci/docker@2.8.2
  keeper: gravitee-io/keeper@0.6.2

commands:
  prepare-docker-context:
    steps:
      - setup_remote_docker
      - keeper/env-export:
          secret-url: keeper://cooU9UoXIk8Kj0hsP2rkBw/field/login
          var-name: DOCKER_LOGIN
      - keeper/env-export:
          secret-url: keeper://cooU9UoXIk8Kj0hsP2rkBw/field/password
          var-name: DOCKER_PASSWORD
      - docker/check

jobs:
  build-and-push-docker-image:
    executor: docker/docker
    steps:
      - checkout
      - prepare-docker-context
      - run:
          name: Build the latest tag and push it to Docker Hub
          command: |
            docker context create tls-env
            docker buildx create tls-env --use
            docker buildx build \
              --push \
              --platform=linux/arm64,linux/amd64 \
              -t graviteeio/gravitee-apim-stats:latest \
              -f docker/Dockerfile \
              docker

workflows:
  build-and-push:
    when:
      and:
        - equal: [ circleci-project-setup, << pipeline.git.branch >> ]
    jobs:
      - build-and-push-docker-image:
          name: build and push docker image
          context: cicd-orchestrator
